### PR TITLE
Consistently use named inner classes instead of anonymous classes for better readability.

### PR DESCRIPTION
**Pull request by luqmana**
A huge return statement instantiating an anonymous class followed by a method call is hard to read. We already split the class out to a named inner class for `EqualityVariableCombos` so let's follow that pattern for Subtype, Inequality and Comparable.

### CODE REVIEW

**Comment by wmdietl** [comment]
@luqmana Can you make sure that the tests either work or fail the same way as master? The changes look good and we should merge this PR.

**Comment by luqmana** [comment]
Ok, updated to master and it's failing in the same: passes on jdk8 and fails on jdk7.

**Comment by wmdietl** [comment]
@CharlesZ-Chen can you have a look at this and see whether updating fixes the errors?
As there are no merge conflicts, it should still be possible to merge.

**Comment by CharlesZ-Chen** [comment]
Sure, will look at this. Currently GTIS failed travis test due to opprop/CFI still failing on travis test:

https://github.com/opprop/checker-framework-inference/pull/45

Will re-try travis test on this PR after making opprop/CFI works again.

**Pull request merged**
